# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_temp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormTemp(object):
    def setupUi(self, FormTemp):
        FormTemp.setObjectName("FormTemp")
        FormTemp.resize(342, 126)
        self.prbTypeComboBox = QtWidgets.QComboBox(FormTemp)
        self.prbTypeComboBox.setGeometry(QtCore.QRect(160, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.prbTypeComboBox.setFont(font)
        self.prbTypeComboBox.setObjectName("prbTypeComboBox")
        self.prbTypeComboBox.addItem("")
        self.prbTypeComboBox.addItem("")
        self.cancelButton = QtWidgets.QPushButton(FormTemp)
        self.cancelButton.setGeometry(QtCore.QRect(192, 80, 111, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(FormTemp)
        self.label.setGeometry(QtCore.QRect(50, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.okButton = QtWidgets.QPushButton(FormTemp)
        self.okButton.setGeometry(QtCore.QRect(40, 80, 111, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")

        self.retranslateUi(FormTemp)
        QtCore.QMetaObject.connectSlotsByName(FormTemp)

    def retranslateUi(self, FormTemp):
        _translate = QtCore.QCoreApplication.translate
        FormTemp.setWindowTitle(_translate("FormTemp", "体温参数设置"))
        self.prbTypeComboBox.setItemText(0, _translate("FormTemp", " YSI"))
        self.prbTypeComboBox.setItemText(1, _translate("FormTemp", "CY-FI"))
        self.cancelButton.setText(_translate("FormTemp", "取消"))
        self.label.setText(_translate("FormTemp", "探头类型："))
        self.okButton.setText(_translate("FormTemp", "确定"))
