# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_savedata_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSaveData(object):
    def setupUi(self, FormSaveData):
        FormSaveData.setObjectName("FormSaveData")
        FormSaveData.resize(642, 181)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        FormSaveData.setFont(font)
        self.pathSelectGroupBox = QtWidgets.QGroupBox(FormSaveData)
        self.pathSelectGroupBox.setGeometry(QtCore.QRect(20, 10, 601, 91))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pathSelectGroupBox.setFont(font)
        self.pathSelectGroupBox.setObjectName("pathSelectGroupBox")
        self.savePathLineEdit = QtWidgets.QLineEdit(self.pathSelectGroupBox)
        self.savePathLineEdit.setGeometry(QtCore.QRect(10, 40, 481, 31))
        self.savePathLineEdit.setObjectName("savePathLineEdit")
        self.openButton = QtWidgets.QPushButton(self.pathSelectGroupBox)
        self.openButton.setGeometry(QtCore.QRect(500, 40, 93, 31))
        self.openButton.setObjectName("openButton")
        self.okButton = QtWidgets.QPushButton(FormSaveData)
        self.okButton.setGeometry(QtCore.QRect(60, 120, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(FormSaveData)
        self.cancelButton.setGeometry(QtCore.QRect(450, 120, 131, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(FormSaveData)
        QtCore.QMetaObject.connectSlotsByName(FormSaveData)

    def retranslateUi(self, FormSaveData):
        _translate = QtCore.QCoreApplication.translate
        FormSaveData.setWindowTitle(_translate("FormSaveData", "文件存储"))
        self.pathSelectGroupBox.setTitle(_translate("FormSaveData", "文件路径"))
        self.openButton.setText(_translate("FormSaveData", "打开"))
        self.okButton.setText(_translate("FormSaveData", "确定"))
        self.cancelButton.setText(_translate("FormSaveData", "取消"))
