# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_nibp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormNIBP(object):
    def setupUi(self, FormNIBP):
        FormNIBP.setObjectName("FormNIBP")
        FormNIBP.resize(301, 151)
        self.startMeasButton = QtWidgets.QPushButton(FormNIBP)
        self.startMeasButton.setGeometry(QtCore.QRect(50, 50, 201, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.startMeasButton.setFont(font)
        self.startMeasButton.setObjectName("startMeasButton")
        self.stopMeasButton = QtWidgets.QPushButton(FormNIBP)
        self.stopMeasButton.setGeometry(QtCore.QRect(50, 100, 201, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.stopMeasButton.setFont(font)
        self.stopMeasButton.setObjectName("stopMeasButton")
        self.label = QtWidgets.QLabel(FormNIBP)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(FormNIBP)
        QtCore.QMetaObject.connectSlotsByName(FormNIBP)

    def retranslateUi(self, FormNIBP):
        _translate = QtCore.QCoreApplication.translate
        FormNIBP.setWindowTitle(_translate("FormNIBP", "血压参数设置"))
        self.startMeasButton.setText(_translate("FormNIBP", "开始测量"))
        self.stopMeasButton.setText(_translate("FormNIBP", "停止测量"))
        self.label.setText(_translate("FormNIBP", "测量状态"))
