# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_resp_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormResp(object):
    def setupUi(self, FormResp):
        FormResp.setObjectName("FormResp")
        FormResp.resize(342, 130)
        self.gainComboBox = QtWidgets.QComboBox(FormResp)
        self.gainComboBox.setGeometry(QtCore.QRect(160, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.gainComboBox.setFont(font)
        self.gainComboBox.setObjectName("gainComboBox")
        self.gainComboBox.addItem("")
        self.gainComboBox.addItem("")
        self.gainComboBox.addItem("")
        self.gainComboBox.addItem("")
        self.gainComboBox.addItem("")
        self.cancelButton = QtWidgets.QPushButton(FormResp)
        self.cancelButton.setGeometry(QtCore.QRect(192, 80, 111, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.okButton = QtWidgets.QPushButton(FormResp)
        self.okButton.setGeometry(QtCore.QRect(40, 80, 111, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.label = QtWidgets.QLabel(FormResp)
        self.label.setGeometry(QtCore.QRect(50, 10, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(FormResp)
        QtCore.QMetaObject.connectSlotsByName(FormResp)

    def retranslateUi(self, FormResp):
        _translate = QtCore.QCoreApplication.translate
        FormResp.setWindowTitle(_translate("FormResp", "呼吸参数设置"))
        self.gainComboBox.setItemText(0, _translate("FormResp", "×0.25"))
        self.gainComboBox.setItemText(1, _translate("FormResp", "×0.5"))
        self.gainComboBox.setItemText(2, _translate("FormResp", "×1"))
        self.gainComboBox.setItemText(3, _translate("FormResp", "×2"))
        self.gainComboBox.setItemText(4, _translate("FormResp", "×4"))
        self.cancelButton.setText(_translate("FormResp", "取消"))
        self.okButton.setText(_translate("FormResp", "确定"))
        self.label.setText(_translate("FormResp", "增益设置："))
