# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_playdata_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormPlayData(object):
    def setupUi(self, FormPlayData):
        FormPlayData.setObjectName("FormPlayData")
        FormPlayData.resize(642, 181)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        FormPlayData.setFont(font)
        self.pathSelectGroupBox = QtWidgets.QGroupBox(FormPlayData)
        self.pathSelectGroupBox.setGeometry(QtCore.QRect(20, 10, 601, 91))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.pathSelectGroupBox.setFont(font)
        self.pathSelectGroupBox.setObjectName("pathSelectGroupBox")
        self.readPathLineEdit = QtWidgets.QLineEdit(self.pathSelectGroupBox)
        self.readPathLineEdit.setGeometry(QtCore.QRect(10, 40, 481, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.readPathLineEdit.setFont(font)
        self.readPathLineEdit.setObjectName("readPathLineEdit")
        self.openButton = QtWidgets.QPushButton(self.pathSelectGroupBox)
        self.openButton.setGeometry(QtCore.QRect(500, 40, 93, 31))
        self.openButton.setObjectName("openButton")
        self.okButton = QtWidgets.QPushButton(FormPlayData)
        self.okButton.setGeometry(QtCore.QRect(60, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(FormPlayData)
        self.cancelButton.setGeometry(QtCore.QRect(470, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(FormPlayData)
        QtCore.QMetaObject.connectSlotsByName(FormPlayData)

    def retranslateUi(self, FormPlayData):
        _translate = QtCore.QCoreApplication.translate
        FormPlayData.setWindowTitle(_translate("FormPlayData", "数据演示"))
        self.pathSelectGroupBox.setTitle(_translate("FormPlayData", "文件路径"))
        self.openButton.setText(_translate("FormPlayData", "打开"))
        self.okButton.setText(_translate("FormPlayData", "确定"))
        self.cancelButton.setText(_translate("FormPlayData", "取消"))
