# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form_spo2_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormSPO2(object):
    def setupUi(self, FormSPO2):
        FormSPO2.setObjectName("FormSPO2")
        FormSPO2.resize(342, 130)
        self.cancelButton = QtWidgets.QPushButton(FormSPO2)
        self.cancelButton.setGeometry(QtCore.QRect(192, 80, 111, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(FormSPO2)
        self.label.setGeometry(QtCore.QRect(40, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.okButton = QtWidgets.QPushButton(FormSPO2)
        self.okButton.setGeometry(QtCore.QRect(40, 80, 111, 28))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.okButton.setFont(font)
        self.okButton.setObjectName("okButton")
        self.sensComboBox = QtWidgets.QComboBox(FormSPO2)
        self.sensComboBox.setGeometry(QtCore.QRect(160, 20, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.sensComboBox.setFont(font)
        self.sensComboBox.setObjectName("sensComboBox")
        self.sensComboBox.addItem("")
        self.sensComboBox.addItem("")
        self.sensComboBox.addItem("")

        self.retranslateUi(FormSPO2)
        QtCore.QMetaObject.connectSlotsByName(FormSPO2)

    def retranslateUi(self, FormSPO2):
        _translate = QtCore.QCoreApplication.translate
        FormSPO2.setWindowTitle(_translate("FormSPO2", "血氧参数设置"))
        self.cancelButton.setText(_translate("FormSPO2", "取消"))
        self.label.setText(_translate("FormSPO2", "计算灵敏度："))
        self.okButton.setText(_translate("FormSPO2", "确定"))
        self.sensComboBox.setItemText(0, _translate("FormSPO2", "高"))
        self.sensComboBox.setItemText(1, _translate("FormSPO2", "中"))
        self.sensComboBox.setItemText(2, _translate("FormSPO2", "低"))
